routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
/**
Route::resource('admin/category', 'Admin\Category\CateController')->middleware('auth:admin');
Route::resource('user/product', 'User\Product\ProdController')->middleware('auth:user');
*/

Route::resource('admin/category', 'Admin\Category\CateController');
Route::resource('user/product', 'User\Product\ProdController');

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::post('/', function () {
    return view('welcome');
});
// User uri

Route::get('user/login', 'User\Auth\LoginController@showLoginForm')->name('user_login_page');
Route::get('/user/register', 'User\Auth\RegisterController@showRegistrationForm')->name('user_register_page');

Route::get('/admin/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login_page');
Route::get('/admin/register','Admin\Auth\RegisterController@showRegistrationForm')->name('admin_register_page');

Route::post('user/login', 'User\Auth\LoginController@login')->name('user.login');
Route::post('admin/login', 'Admin\Auth\LoginController@login')->name('admin.login');

Route::post('user/register','User\Auth\RegisterController@register')->name('user.register');
Route::post('admin/register','Admin\Auth\RegisterController@register')->name('admin.register');

Route::post('logout','User\Auth\LoginController@logout')->name('logout');

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/home', 'User\UserController@index')->name('user.home');
Route::get('/admin/home', 'Admin\AdminController@index')->name('admin.home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{


    protected $fillable = [
        'name',
        'description',
        'category_id',
        'price',
        'expire_at'
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'name', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/Product/ProdController.php
<?php

namespace App\Http\Controllers\User\Product;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class ProdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();

        return view('user.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('user.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name'=>['required', 'string', 'min:3', 'unique:products'],
            'description'=>['required', 'min:5'],
            'category_id' => ['required', 'integer'],
            'price' => ['required', 'integer'],
            'expire_at' => ['required', 'after'],
        ]);

        $contact = new Product([
            'name' => $request->get('name'),
            'description' => $request->get('description'),
            'category_id' => $request->get('category_id'),
            'price' => $request->get('price'),
            'expire_at' => $request->get('expire_at')
        ]);
        $contact->save();
        return redirect()->route('product.index')->with('success', 'product saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);

        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $categories = Category::all();

        return view('user.product.edit', compact('product', 'categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>['required', 'string', 'min:3', Rule::unique('products')->ignore($id)],
            'description'=>['required', 'min:5'],
            'category_id' => ['required', 'integer', ],
            'price' => ['required', 'integer'],
            'expire_at' => ['required', 'after'],
        ]);

        $product = Product::find($id);
        $product->name = $request->get('name');
        $product->description = $request->get('description');
        $product->category_id = $request->get('category_id');
        $product->price = $request->get('price');
        $product->expire_at = $request->get('expire_at');
        $product->save();

        return redirect()->route('product.index')->with('success', 'Product updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Product::find($id);
        $contact->delete();

        return redirect()->route('product.index')->with('success', 'Product deleted!');
    }

}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

    // users controller
    public function login(){
        return \view('user.auth.login');
    }

    public function register(){
        return \view('user.auth.register');
    }

    public function index(){
        return view('user.auth.home');
    }


}

resources/views/user/product/create.blade.php
@extends('layouts.base')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Product') }}</div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('product.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>
                                <div class="col-md-6">
                                    <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('name') }}"></textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="category_id" class="col-md-4 col-form-label text-md-right">{{ __('Category') }}</label>
                                <div class="col-md-6">
                                    <select id="category_id" class="form-control" @error('category_id') is-invalid @enderror name="category_id" value="{{ old('category_id') }}" >
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}} </option>
                                        @endforeach
                                    </select>
                                    {{--
                                    <input id="category_id" type="number" class="form-control @error('category_id') is-invalid @enderror" name="category_id" value="{{ old('category_id') }}">
--}}
                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>
                                <div class="col-md-6">
                                    <input id="price" type="number" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}">

                                    @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="expire_at" class="col-md-4 col-form-label text-md-right">{{ __('Expire at') }}</label>
                                <div class="col-md-6">
                                    <input id="expire_at" type="date" class="form-control @error('expire_at') is-invalid @enderror" name="expire_at" value="{{ old('expire_at') }}">

                                    {{--
                                    <input type="date" name="date" id="date" class="form-control" style="width: 100%; display: inline;" onchange="invoicedue(event);" required value="{{$shipment->date}}">
--}}
                                    @error('expire_at')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Store') }}
                                    </button>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/product/edit.blade.php
@extends('layouts.base')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Product') }}</div>

                    <div class="card-body">

                        <form method="post" action="{{ route('product.update', $product) }}">
                            @csrf
                            {{--   {{ method_field('PUT') }}  --}}
                            <input type="hidden" name="_method" value="PUT">

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $product->name }}">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>
                                <div class="col-md-6">
                                    <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" >{{ $product->description }}</textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="category_id" class="col-md-4 col-form-label text-md-right">{{ __('Category') }}</label>
                                <div class="col-md-6">
                                    <select id="category_id" class="form-control" @error('category_id') is-invalid @enderror name="category_id" value="{{ old('category_id') }}" >
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}} </option>
                                        @endforeach
                                    </select>
                                    {{--
                                    <input id="category_id" type="number" class="form-control @error('category_id') is-invalid @enderror" name="category_id" value="{{ old('category_id') }}">
--}}
                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>
                                <div class="col-md-6">
                                    <input id="price" type="number" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $product->price }}">

                                    @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="expire_at" class="col-md-4 col-form-label text-md-right">{{ __('Expire at') }}</label>
                                <div class="col-md-6">
                                    <input id="expire_at" type="date" class="form-control @error('expire_at') is-invalid @enderror" name="expire_at" value="{{ $product->expire_at }}">

                                    @error('expire_at')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/product/index.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h3 class="display-3">Products</h3>

            <a href="{{ route('product.create')}}" class="btn btn-success btn-lg">Create</a>
            <a href="{{ route('user.home')}}" class="btn btn-success btn-lg">Home</a>

            @if(count($products) > 0)
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>ID</td>
                        <td>Name</td>
                        <td>Description</td>
                        <td>category</td>
                        <td>price</td>
                        <td>expire_at</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)

                        <tr>
                            <td>{{$product->id}}</td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->description}}</td>
                            <td>{{$product->category->name}}</td>
                            <td>{{$product->price}}</td>
                            <td>{{$product->expire_at}}</td>

                            <td>
                                <a href="{{ route('product.show',$product->id)}}" class="btn btn-primary">Show</a>
                            </td>
                            <td>
                                <a href="{{ route('product.edit',$product->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <form action="{{ route('product.destroy', $product->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h4 style="color:#01549b">Aucun événement pour le moment</h4>
            @endif
            <div>
            </div>
@endsection

resources/views/user/product/show.blade.php
@extends('layouts.base')

@section('content')
    <div align="center" class="row">
        <div class="col-sm-12">
            <h3 class="display-4"> Produit N°{{ $product->id }}</h3>

            <p><label class="field left">Name : </label> <input type="text" value="{{$product->name}}" class="field left" readonly></p>
            <p><label class="field left">Description : </label> <input type="text" value="{{$product->description}}" class="field left" readonly></p>
            <p><label class="field left">Category id : </label> <input type="text" value="{{$product->category_id}}" class="field left" readonly></p>
            <p><label>Price : </label> <input type="text" value="{{$product->price}}" class="field left" readonly></p>
            <p><label>Expire at : </label> <input type="text" value="{{$product->expire_at}}" class="field left" readonly></p>
        </div>
    </div>
@endsection